stages:
  pre_processing:
    cmd: python src/pre_processing.py
    deps:
    - data/raw
    outs:
    - data/processed
  modeling:
    cmd: python src/modeling.py
    deps:
    - data/processed
    - src/pre_processing
    outs:
    - random_model_1.pkl
  feature:
    cmd: engineering -d data/processed -d src/pre_processing.py -o added_features.csv
      python src/feature_engineering
