stages:
  pre_processing:
    cmd: python src/pre_processing.py
    deps:
    - data/raw
    outs:
    - data/processed
  feature:
    cmd: engineering -d data/processed -d src/pre_processing.py -o added_features.csv
      python src/feature_engineering
    outs:
    - data/featured
  model_building:
    cmd: python src/modeling.py
    deps:
    - data/featured
    - src/modeling.py
    outs:
    - trained_model.pkl
  model_evaluation:
    cmd: python src/evaluation.py
    deps:
    - data/model
    - src/evaluation.py
    metrics:
    - metrics.json
